server:
  port: 9000

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka
zuul:
  routes:
    users:
      path: /myproduct/**
      serviceId: product
      strip-prefix: false

spring:
  application:
    name: api-gateway