server:
  port: 8762

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: server02hostname
spring:
  application:
    name: eureka02